### ISSUE TITLE
Progression bar when cutting never end

### ISSUE THREAD

**Issue by Hboni** [deplanty/video-cutter-tags#2]
I had a video with several selection, but without any tag. I wanted to save cuts sing the scissor symbol. It exported all my cuts separately and the merge of all cuts.
But the window with bar progression about cuts did not close itself, and the bar never loops, going from 0% to 100% all the time.
Is the window intended to close itself or we have to click on the "OK" button?

**Comment by deplanty** [comment]
Thank you for your issue.
The window is meant to stay open until the "Ok" button is clicked.
When the cuts are exported, the progress bar should stop looping.
